name: enigma
description: "Enigma is a secure data storage application designed to safeguard your sensitive information and credentials. With Enigma, you can trust that your data remains private and secure, protected by advanced cryptographic techniques."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  local_auth: ^2.2.0
  get: ^4.6.6
  google_fonts: ^6.2.1
#  restart_app: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true































